const data = {
    products:[
        {
            _id: '1',
            name: 'Amoxicillin Capsules',
            slug: 'amoxicillin-capsules',
            category: 'Painkiller',
            image: '/images/amoxicillinCapsules.png',
            price: 320,
            countInStock: 0,
            treats: 'headache,',
            rating: 4.5,
            numReviews: 10,
            description: 'This painkiller reduces headache, sorethrout and body pains'
        },
        {
            _id: '2',
            name: 'Artemether-lumefantrine',
            slug: 'artemether-lumefantrine',
            category: 'anti=biotic',
            image: '/images/Artemether-Lumefantrine.webp',
            price: 150,
            countInStock: 12,
            treats: 'Malaria',
            rating: 4.5,
            numReviews: 96,
            description: 'Artemether/lumefantrine, sold under the trade name Coartem among others, is a combination of the two medications artemether and lumefantrine. It is used to treat malaria caused by Plasmodium falciparum that is not treatable with chloroquine.'
        },
        {
            _id: '3',
            name: 'Paracetamol',
            slug: 'panadol',
            category: 'Painkiller',
            image: '/images/paracetamol.jpg',
            price: 99,
            countInStock: 3,
            treats: 'Pain',
            rating: 4.5,
            numReviews: 120,
            description: 'It is a medication used to treat fever and mild to moderate pain.'
        },
        {
            _id: '4',
            name: 'cough syrup',
            slug: 'cough-syrup',
            category: 'Curative',
            image: '/images/cough-syrup.jpg',
            price: 700,
            countInStock: 5,
            treats: 'Breathing',
            rating: 4.5,
            numReviews: 50,
            description: 'It is a medication taken individually or in combination as a treatment for the symptoms of the common cold and similar conditions of the upper respiratory tract.'
        },
        {
            _id: '5',
            name: 'antacid tablet',
            slug: 'antacid-tablet',
            category: 'sedatives',
            image: '/images/antacid.webp',
            price: 150,
            countInStock: 10,
            treats: 'heartburn',
            rating: 4.5,
            numReviews: 70,
            description: 'Antacids are medicines that counteract (neutralise) the acid in your stomach to relieve indigestion and heartburn'
        },
        {
            _id: '6',
            name: 'Lisinopril',
            slug: 'lisinopril',
            category: 'Curative',
            image: '/images/lisinopril.jpg',
            price: 1950,
            countInStock: 20,
            treats: 'blood pressure',
            rating: 4.5,
            numReviews: 111,
            description: 'Lowering blood pressure can reduce the risk of strokes and heart attacks. Lisinopril works by blocking a substance in the body that causes the blood vessels to tighten. As a result, lisinopril relaxes the blood vessels. This lowers blood pressure and increases the supply of blood and oxygen to the heart.'
        },
        {
            _id: '7',
            name: 'Metformin',
            slug: 'metformin',
            category: 'Curative',
            image: '/images/Metformin.jpg',
            price: 1200,
            countInStock: 70,
            treats: 'Diabetes',
            rating: 4.5,
            numReviews: 62,
            description: 'Metformin lowers your blood sugar levels by improving the way your body handles insulin. It is usually prescribed for diabetes when diet and exercise alone have not been enough to control your blood sugar levels.'
        },
        {
            _id: '8',
            name: 'Amlodipine',
            slug: 'amlodipine',
            category: 'Curative',
            image: '/images/amlodipine-tablets.jpeg',
            price: 1500,
            countInStock: 60,
            treats: 'blood pressure',
            rating: 4.5,
            numReviews: 50,
            description: ' is used alone or in combination with other medications to treat high blood pressure in adults and children 6 years and older.'
        },
        {
            _id: '9',
            name: 'Omeprazole',
            slug: 'omeprazole',
            category: 'Curative',
            image: '/images/Omeprazole.webp',
            price: 800,
            countInStock: 100,
            treats: 'stomach acid',
            rating: 4.5,
            numReviews: 30,
            description: 'Omeprazole: a medicine to treat heartburn and indigestion'
        },
        {
            _id: '10',
            name: 'slimming tea ',
            slug: 'slimming tea ',
            category: 'stumilant',
            image: '/images/slimming-tea.jpg',
            price: 1015,
            countInStock: 50,
            treats: 'weight loss',
            rating: 4.5,
            numReviews: 16,
            description: 'Slimming tea is often advertised as a way to lose weight and cleanse the body. The theory is that the tea stimulates digestion, aids metabolism, and, in some cases, rids the body of impurities'
        },
    
    ],
};
 export default data;